import { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import { analyzeSmsFinances, getMonthlyFinances, type MonthlyFinance } from '../planner/expenseClient';
import { getSmsInboxModule } from '../native/SmsInbox';
import { connectGoogleAccountTool } from '../tools/registry';
import { BACKEND_BASE_URL } from '../config/backend';
import { colors } from '../theme';
import { GradientButton } from './GradientButton';

const SMS_LOOKBACK_HOURS = 744; // native cap (31 days); analyzeSmsFinances filters to the requested month

export function ExpenseDashboardCard() {
  const now = new Date(); const [year, setYear] = useState(String(now.getFullYear())); const [month, setMonth] = useState(String(now.getMonth() + 1)); const [data, setData] = useState<MonthlyFinance | null>(null); const [analysis, setAnalysis] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [connecting, setConnecting] = useState(false);
  async function applyResult(result: MonthlyFinance) { setData(result); const response = await fetch(`${BACKEND_BASE_URL}/expenses/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ finances: result }) }); const json = await response.json(); if (response.ok) setAnalysis(json.analysis ?? ''); }
  async function loadFromGmail() { setBusy(true); setError(null); try { await applyResult(await getMonthlyFinances(Number(year), Number(month))); } catch (e) { setError(e instanceof Error ? e.message : 'Finance load failed.'); } finally { setBusy(false); } }
  async function loadFromSms() { setBusy(true); setError(null); try { const messages = await getSmsInboxModule().getRecentSms(SMS_LOOKBACK_HOURS); await applyResult(await analyzeSmsFinances(Number(year), Number(month), messages)); } catch (e) { setError(e instanceof Error ? e.message : 'SMS finance load failed.'); } finally { setBusy(false); } }
  async function connectGoogle() { setConnecting(true); try { await connectGoogleAccountTool.execute(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not open Google sign-in.'); } finally { setConnecting(false); } }
  const needsGoogleConnect = /connect a google account/i.test(error ?? '');
  const categories: Record<string, number> = {}; data?.items.filter((item) => item.type === 'expense').forEach((item) => { categories[item.category] = (categories[item.category] ?? 0) + item.amount; }); const max = Math.max(1, ...Object.values(categories));
  return <View style={styles.card}><Text style={styles.title}>Finance overview</Text><Text style={styles.description}>Review expenses and revenue by month, derived from your connected Gmail or from on-device bank/mobile-money SMS. Values remain candidates until you confirm them.</Text><View style={styles.row}><TextInput style={styles.input} value={year} onChangeText={setYear} keyboardType="numeric" placeholder="Year" placeholderTextColor={colors.textMuted} /><TextInput style={styles.input} value={month} onChangeText={setMonth} keyboardType="numeric" placeholder="Month" placeholderTextColor={colors.textMuted} /></View><View style={styles.row}><GradientButton label={busy ? 'Analyzing...' : 'Load from Gmail'} disabled={busy} onPress={() => void loadFromGmail()} style={styles.buttonHalf} /><GradientButton label={busy ? 'Analyzing...' : 'Load from SMS'} disabled={busy} onPress={() => void loadFromSms()} style={styles.buttonHalf} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}{needsGoogleConnect ? <GradientButton label={connecting ? 'Opening Google sign-in...' : 'Connect Google Account'} disabled={connecting} onPress={() => void connectGoogle()} style={styles.connectButton} /> : null}{data ? <><Text style={styles.summary}>Expenses and revenue are grouped by currency. {data.items.length} candidate item(s).</Text>{Object.entries(categories).map(([category, value]) => <View key={category} style={styles.barRow}><Text style={styles.category}>{category}</Text><View style={styles.track}><View style={[styles.bar, { width: `${(value / max) * 100}%` }]} /></View><Text style={styles.amount}>{value.toLocaleString()}</Text></View>)}{analysis ? <Text style={styles.analysis}>{analysis}</Text> : null}</> : null}</View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, marginBottom: 16, padding: 16 }, title: { color: colors.textPrimary, fontSize: 16, fontWeight: '800' }, description: { color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginBottom: 12, marginTop: 6 }, row: { flexDirection: 'row', gap: 8, marginBottom: 10 }, input: { backgroundColor: colors.surfaceAlt, borderColor: colors.border, borderRadius: 8, borderWidth: 1, color: colors.textPrimary, flex: 1, minHeight: 44, paddingHorizontal: 10 }, buttonHalf: { flex: 1 }, connectButton: { marginTop: 10 }, summary: { color: colors.textSecondary, fontSize: 12, marginTop: 12 }, barRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 10 }, category: { color: colors.textSecondary, width: 70 }, track: { backgroundColor: colors.surfaceAlt, borderRadius: 5, flex: 1, height: 10, overflow: 'hidden' }, bar: { backgroundColor: colors.accent, height: 10 }, amount: { color: colors.textPrimary, fontSize: 12, width: 74 }, analysis: { backgroundColor: colors.infoBg, borderColor: colors.infoBorder, borderRadius: 8, borderWidth: 1, color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 14, padding: 10 }, error: { color: colors.dangerText, marginTop: 10 } });
