import { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import { getMonthlyFinances, type MonthlyFinance } from '../planner/expenseClient';
import { BACKEND_BASE_URL } from '../config/backend';
import { colors } from '../theme';
import { GradientButton } from './GradientButton';

export function ExpenseDashboardCard() {
  const now = new Date(); const [year, setYear] = useState(String(now.getFullYear())); const [month, setMonth] = useState(String(now.getMonth() + 1)); const [data, setData] = useState<MonthlyFinance | null>(null); const [analysis, setAnalysis] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { setBusy(true); setError(null); try { const result = await getMonthlyFinances(Number(year), Number(month)); setData(result); const response = await fetch(`${BACKEND_BASE_URL}/expenses/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ finances: result }) }); const json = await response.json(); if (response.ok) setAnalysis(json.analysis ?? ''); } catch (e) { setError(e instanceof Error ? e.message : 'Finance load failed.'); } finally { setBusy(false); } }
  const categories: Record<string, number> = {}; data?.items.filter((item) => item.type === 'expense').forEach((item) => { categories[item.category] = (categories[item.category] ?? 0) + item.amount; }); const max = Math.max(1, ...Object.values(categories));
  return <View style={styles.card}><Text style={styles.title}>Finance overview</Text><Text style={styles.description}>Review email-derived expenses and revenue by month. Values remain candidates until you confirm them.</Text><View style={styles.row}><TextInput style={styles.input} value={year} onChangeText={setYear} keyboardType="numeric" placeholder="Year" placeholderTextColor={colors.textMuted} /><TextInput style={styles.input} value={month} onChangeText={setMonth} keyboardType="numeric" placeholder="Month" placeholderTextColor={colors.textMuted} /></View><GradientButton label={busy ? 'Analyzing...' : 'Load monthly finances'} disabled={busy} onPress={() => void load()} />{error ? <Text style={styles.error}>{error}</Text> : null}{data ? <><Text style={styles.summary}>Expenses and revenue are grouped by currency. {data.items.length} candidate item(s).</Text>{Object.entries(categories).map(([category, value]) => <View key={category} style={styles.barRow}><Text style={styles.category}>{category}</Text><View style={styles.track}><View style={[styles.bar, { width: `${(value / max) * 100}%` }]} /></View><Text style={styles.amount}>{value.toLocaleString()}</Text></View>)}{analysis ? <Text style={styles.analysis}>{analysis}</Text> : null}</> : null}</View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, marginBottom: 16, padding: 16 }, title: { color: colors.textPrimary, fontSize: 16, fontWeight: '800' }, description: { color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginBottom: 12, marginTop: 6 }, row: { flexDirection: 'row', gap: 8, marginBottom: 10 }, input: { backgroundColor: colors.surfaceAlt, borderColor: colors.border, borderRadius: 8, borderWidth: 1, color: colors.textPrimary, flex: 1, minHeight: 44, paddingHorizontal: 10 }, summary: { color: colors.textSecondary, fontSize: 12, marginTop: 12 }, barRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 10 }, category: { color: colors.textSecondary, width: 70 }, track: { backgroundColor: colors.surfaceAlt, borderRadius: 5, flex: 1, height: 10, overflow: 'hidden' }, bar: { backgroundColor: colors.accent, height: 10 }, amount: { color: colors.textPrimary, fontSize: 12, width: 74 }, analysis: { backgroundColor: colors.infoBg, borderColor: colors.infoBorder, borderRadius: 8, borderWidth: 1, color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 14, padding: 10 }, error: { color: colors.dangerText, marginTop: 10 } });
